Tabolich lesson 2
vladislav-tarasov-tms/js-basic_FE60 pull request #28
Opened 2021-09-19 20:53 UTC by DzmitryTabolich

Please check my second homework.

2021-09-20 09:31 UTC, vladislav-tarasov-tms commented on README.md
> +#### Структура
эти файлы должны были уже быть в ветке Tabolich

2021-09-20 09:31 UTC, vladislav-tarasov-tms commented on lesson-2/homework/script.js
> +const keys = Object.keys(obj);
олжна быть логика через цикл по объекту!

2021-09-20 09:31 UTC, vladislav-tarasov-tms commented on lesson-2/homework/script.js
> +    even[i] = i;
у нас тогда выйдет результат even = [undefined, undefined, 2, undefined, 4]
а нужно even = [2,4,6,8,10,12]

2021-09-20 11:31 UTC, DzmitryTabolich commented on lesson-2/homework/script.js
> +    even[i] = i;
Please check now

2021-09-20 11:33 UTC, DzmitryTabolich commented on lesson-2/homework/script.js
> +const keys = Object.keys(obj);
Использовал for of и for in со звездочкой не понял че надо

2021-09-21 15:07 UTC, vladislav-tarasov-tms requested changes

2021-09-21 15:07 UTC, vladislav-tarasov-tms commented on lesson-2/homework/script.js
> +  sum += i;
только надо прибавлять не индекс, а элемент массива по индексу

2021-09-21 15:07 UTC, vladislav-tarasov-tms commented on lesson-2/homework/script.js
> +    multi *= i;
тож самое)

2021-09-21 15:07 UTC, vladislav-tarasov-tms commented on lesson-2/homework/script.js
> +  } else if (nums3[i] < min) {
`else if` будет лишним! 
вдруг у нас массив только с одним числом? тогда оно должно быть одновременно и `max` и `min`

2021-09-21 15:07 UTC, vladislav-tarasov-tms commented on lesson-2/homework/script.js
> +for (let key in Object.values(obj)) {
надо обратиться к объекту по ключи чтобы получить значение!

2021-10-04 18:07 UTC, merged